// src/templates/beauty/glow/demo-data.ts

export const GLOW_DEMO = {
  store: {
    id: "demo",
    name: "Glow Beauty",
    brandName: "Glow",
    tagline: "Radiant every day",
    about: "Clean beauty crafted with care.",
    address: "Mumbai, India",
  },

  products: [
    {
      id: "demo-1",
      name: "Glow Serum",
      description: "Brightening vitamin C serum",
      image: "https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 1499,
      compareAt: 1999,
      category: "skincare",
      tags: ["skincare", "serum"],
      rating: 4.8,
      inventory: 25,
      metadata: {
        ingredients: ["Vitamin C", "Niacinamide"],
        volume: "30ml",
        vegan: true,
      },
    },
    {
      id: "demo-2",
      name: "Rose Face Mist",
      description: "Refreshing rose water mist",
      image: "https://images.pexels.com/photos/3727255/pexels-photo-3727255.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 499,
      category: "skincare",
      tags: ["skincare", "mist"],
      rating: 4.7,
      inventory: 40,
      metadata: { volume: "100ml", vegan: true },
    },
    {
      id: "demo-3",
      name: "Glow Lip Balm",
      description: "Hydrating tinted lip balm",
      image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 349,
      category: "makeup",
      tags: ["makeup", "lips"],
      rating: 4.6,
      inventory: 50,
      metadata: {
        shades: ["Rose", "Berry", "Nude"],
        vegan: true,
      },
    },
    {
      id: "demo-4",
      name: "Nourishing Hair Oil",
      description: "Argan oil for shiny hair",
      image: "https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 799,
      category: "haircare",
      tags: ["haircare"],
      rating: 4.5,
      inventory: 30,
      metadata: { volume: "100ml" },
    },
    {
      id: "demo-5",
      name: "Body Butter",
      description: "Shea butter body moisturizer",
      image: "https://images.pexels.com/photos/3997989/pexels-photo-3997989.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 599,
      category: "body",
      tags: ["body"],
      rating: 4.7,
      inventory: 25,
      metadata: { weight: "200g" },
    },
    {
      id: "demo-6",
      name: "Vitamin C Tablets",
      description: "Skin glow supplements",
      image: "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 899,
      category: "wellness",
      tags: ["wellness"],
      rating: 4.6,
      inventory: 40,
    },
  ],

  categories: [
    { id: "skincare", slug: "skincare", name: "Skincare", count: 2 },
    { id: "makeup", slug: "makeup", name: "Makeup", count: 1 },
    { id: "haircare", slug: "haircare", name: "Haircare", count: 1 },
    { id: "body", slug: "body", name: "Body", count: 1 },
    { id: "wellness", slug: "wellness", name: "Wellness", count: 1 },
  ],
};