// src/templates/grocery/fresh/demo-data.ts

export const FRESH_DEMO = {
  store: {
    id: "demo",
    name: "Fresh Market",
    brandName: "Fresh",
    tagline: "Farm-fresh in 12 hours",
    about: "Handpicked, quality-checked, always fresh.",
    address: "Mumbai, India",
  },

  products: [
    {
      id: "demo-1",
      name: "Organic Bananas",
      description: "Fresh organic bananas",
      image: "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 60,
      category: "fruits",
      tags: ["fruits", "organic"],
      rating: 4.7,
      inventory: 50,
      metadata: { weight: "1kg", organic: true, expiryDays: 5 },
    },
    {
      id: "demo-2",
      name: "Fresh Tomatoes",
      description: "Farm-fresh tomatoes",
      image: "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 40,
      category: "vegetables",
      tags: ["vegetables"],
      rating: 4.6,
      inventory: 40,
      metadata: { weight: "500g", expiryDays: 7 },
    },
    {
      id: "demo-3",
      name: "Organic Spinach",
      description: "Fresh organic spinach",
      image: "https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 30,
      category: "vegetables",
      tags: ["vegetables", "organic"],
      rating: 4.8,
      inventory: 35,
      metadata: { weight: "250g", organic: true, expiryDays: 3 },
    },
    {
      id: "demo-4",
      name: "Fresh Milk",
      description: "Farm-fresh cow milk",
      image: "https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 60,
      category: "dairy",
      tags: ["dairy"],
      rating: 4.9,
      inventory: 60,
      metadata: { weight: "1L", expiryDays: 2, storage: "Refrigerate" },
    },
    {
      id: "demo-5",
      name: "Organic Eggs",
      description: "Free-range organic eggs",
      image: "https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 120,
      category: "dairy",
      tags: ["dairy", "organic"],
      rating: 4.7,
      inventory: 30,
      metadata: { weight: "12 pcs", organic: true, expiryDays: 14 },
    },
    {
      id: "demo-6",
      name: "Whole Wheat Bread",
      description: "Fresh baked bread",
      image: "https://images.pexels.com/photos/1387070/pexels-photo-1387070.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 45,
      category: "bakery",
      tags: ["bakery"],
      rating: 4.5,
      inventory: 25,
      metadata: { weight: "400g", expiryDays: 4 },
    },
  ],

  categories: [
    { id: "fruits", slug: "fruits", name: "Fruits", count: 1 },
    { id: "vegetables", slug: "vegetables", name: "Vegetables", count: 2 },
    { id: "dairy", slug: "dairy", name: "Dairy", count: 2 },
    { id: "bakery", slug: "bakery", name: "Bakery", count: 1 },
  ],
};