// src/templates/beauty/lumiere/demo-data.ts
// 🎯 DEMO SEED — Preview + initial store fill

export const LUMIERE_DEMO = {
  store: {
    id: "demo",
    name: "Lumière",
    brandName: "Lumière",
    tagline: "Radiance, reimagined",
    about: "Conscious beauty, crafted with care.",
    address: "Mumbai, India",
  },

  products: [
    {
      id: "demo-1",
      name: "Radiance Serum",
      description: "Vitamin C serum for luminous skin",
      image: "https://images.pexels.com/photos/3762879/pexels-photo-3762879.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 1899,
      compareAt: 2499,
      category: "skincare",
      tags: ["skincare", "serum"],
      rating: 4.9,
      inventory: 25,
      metadata: {
        shades: ["Rose Gold", "Coral", "Nude"],
        skinTypes: ["oily", "combination"],
        ingredients: ["Vitamin C", "Hyaluronic Acid"],
        volume: "30ml",
        vegan: true,
      },
    },
    {
      id: "demo-2",
      name: "Hydra Moisturizer",
      description: "Deep hydration for glowing skin",
      image: "https://images.pexels.com/photos/3735622/pexels-photo-3735622.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 1299,
      category: "skincare",
      tags: ["skincare", "hydration"],
      rating: 4.8,
      inventory: 25,
      metadata: {
        shades: ["Pearl", "Rose"],
        skinTypes: ["dry", "normal"],
        ingredients: ["Ceramides", "Squalane"],
        volume: "50ml",
        vegan: true,
      },
    },
    {
      id: "demo-3",
      name: "Velvet Matte Lipstick",
      description: "Long-lasting matte finish",
      image: "https://images.pexels.com/photos/2536965/pexels-photo-2536965.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 899,
      category: "makeup",
      tags: ["makeup", "lipstick"],
      rating: 4.7,
      inventory: 30,
      metadata: {
        shades: ["Berry", "Coral", "Nude"],
        ingredients: ["Shea Butter", "Vitamin E"],
        volume: "3.5g",
        vegan: true,
      },
    },
    {
      id: "demo-4",
      name: "Silk Hair Oil",
      description: "Nourishing oil for shiny hair",
      image: "https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 749,
      category: "haircare",
      tags: ["haircare", "oil"],
      rating: 4.6,
      inventory: 20,
      metadata: {
        volume: "100ml",
        ingredients: ["Argan Oil", "Jojoba"],
      },
    },
    {
      id: "demo-5",
      name: "Rose Body Scrub",
      description: "Exfoliating scrub with rose extract",
      image: "https://images.pexels.com/photos/3997989/pexels-photo-3997989.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 699,
      category: "body",
      tags: ["body", "scrub"],
      rating: 4.7,
      inventory: 25,
    },
    {
      id: "demo-6",
      name: "Floral Perfume",
      description: "Floral fragrance with lasting notes",
      image: "https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 2499,
      category: "fragrance",
      tags: ["fragrance"],
      rating: 4.9,
      inventory: 15,
      metadata: {
        volume: "50ml",
      },
    },
    {
      id: "demo-7",
      name: "Glow Wellness Tea",
      description: "Herbal tea blend for skin health",
      image: "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 499,
      category: "wellness",
      tags: ["wellness", "tea"],
      rating: 4.5,
      inventory: 40,
    },
    {
      id: "demo-8",
      name: "Vitamin C Face Wash",
      description: "Brightening cleanser",
      image: "https://images.pexels.com/photos/3727255/pexels-photo-3727255.jpeg?auto=compress&cs=tinysrgb&w=800",
      price: 599,
      category: "skincare",
      tags: ["skincare", "cleanser"],
      rating: 4.8,
      inventory: 35,
    },
  ],

  categories: [
    { id: "skincare", slug: "skincare", name: "Skincare", count: 3 },
    { id: "makeup", slug: "makeup", name: "Makeup", count: 1 },
    { id: "haircare", slug: "haircare", name: "Haircare", count: 1 },
    { id: "body", slug: "body", name: "Body", count: 1 },
    { id: "fragrance", slug: "fragrance", name: "Fragrance", count: 1 },
    { id: "wellness", slug: "wellness", name: "Wellness", count: 1 },
  ],
};